### ISSUE TITLE
Can you publish new version on crates.io?

### ISSUE THREAD

**Issue by jeizsm** [alexcrichton/cookie-rs#105]
I want use rustls with cookie, but it depends on ring 0.13.0-alpha

**Comment by SergioBenitez** [comment]
No, sorry. `ring v0.13.0-alpha` is not semver compatible with any other `alpha` version, and due to `ring`'s linking issues (see https://github.com/briansmith/ring/issues/535, https://github.com/briansmith/ring/pull/619), this would mean we'd need to release a new major version for every `alpha` release. As such, we'll wait until either https://github.com/briansmith/ring/pull/619 is merged and/or `ring v0.13` is released.

**Comment by r-arias** [comment]
[ring v0.13.2](https://crates.io/crates/ring/0.13.2) seems to be out. Is there any chance a new `cookie` version will be released soon? [ring v0.12.0 does not build on Windows...](https://github.com/briansmith/ring/issues/667)

**Comment by SergioBenitez** [comment]
A new release has been published.
